import { User, Post, Activity, Message, Story, ActivityComment } from './types';

export const currentBabyUser: User = {
  id: 'baby-1',
  username: 'emma.lifestyle',
  full_name: 'Emma Laurent',
  user_type: 'baby',
  bio: '✨ Living my best life | Travel enthusiast 🌍 | Fashion & lifestyle | Paris 🇫🇷',
  avatar_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
  verified: true,
  is_vip: false,
  followers_count: 2847,
  following_count: 431,
  connections_count: 2,
};

export const currentDaddyUser: User = {
  id: 'daddy-1',
  username: 'alexandre.prestige',
  full_name: 'Alexandre Moreau',
  user_type: 'daddy',
  bio: '🎯 Entrepreneur | Wine connoisseur 🍷 | Luxury lifestyle | Sharing unique experiences',
  avatar_url: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
  verified: true,
  is_vip: true,
  followers_count: 5621,
  following_count: 289,
  connections_count: 4,
};

export const otherUsers: User[] = [
  {
    id: 'daddy-2',
    username: 'thomas.lux',
    full_name: 'Thomas Dubois',
    user_type: 'daddy',
    bio: '🏎️ Fast cars & fine dining | CEO | Monaco resident',
    avatar_url: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=400',
    verified: true,
    is_vip: true,
    followers_count: 8234,
    following_count: 156,
  },
  {
    id: 'baby-2',
    username: 'sophia.travels',
    full_name: 'Sophia Martin',
    user_type: 'baby',
    bio: 'Adventure seeker | Art lover 🎨 | Living in the moment',
    avatar_url: 'https://images.pexels.com/photos/1310522/pexels-photo-1310522.jpeg?auto=compress&cs=tinysrgb&w=400',
    verified: true,
    is_vip: false,
    followers_count: 1456,
    following_count: 523,
  },
  {
    id: 'daddy-3',
    username: 'pierre.elite',
    full_name: 'Pierre Lefebvre',
    user_type: 'daddy',
    bio: '⛵ Yacht life | Private jets | Creating memories',
    avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    verified: true,
    is_vip: true,
    followers_count: 12043,
    following_count: 234,
  },
  {
    id: 'baby-3',
    username: 'chloe.paris',
    full_name: 'Chloé Bernard',
    user_type: 'baby',
    bio: 'Fashion student | Coffee addict ☕ | Paris is always a good idea',
    avatar_url: 'https://images.pexels.com/photos/1845534/pexels-photo-1845534.jpeg?auto=compress&cs=tinysrgb&w=400',
    verified: false,
    is_vip: false,
    followers_count: 892,
    following_count: 678,
  },
];

export const babyPosts: Post[] = [
  {
    id: 'post-1',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1371360/pexels-photo-1371360.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Santorini sunsets hit different 🌅✨ #LivingMyBestLife',
    created_at: '2024-01-15T18:30:00Z',
  },
  {
    id: 'post-2',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1008155/pexels-photo-1008155.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Michelin star dinner in Paris 🍽️✨ Life is beautiful',
    created_at: '2024-01-12T20:15:00Z',
  },
  {
    id: 'post-3',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1591373/pexels-photo-1591373.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Weekend getaway to the French Riviera 🌊💎',
    created_at: '2024-01-08T16:45:00Z',
  },
  {
    id: 'post-4',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Shopping therapy at Champs-Élysées 🛍️💕',
    created_at: '2024-01-05T14:20:00Z',
  },
  {
    id: 'post-5',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1024967/pexels-photo-1024967.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Private yacht day ⛵ Thank you for this amazing experience!',
    created_at: '2024-01-02T12:00:00Z',
  },
  {
    id: 'post-6',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1268855/pexels-photo-1268855.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Dubai nights 🌃✨ Living the dream',
    created_at: '2023-12-28T22:30:00Z',
  },
];

export const daddyPosts: Post[] = [
  {
    id: 'post-d1',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/3593922/pexels-photo-3593922.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'New acquisition for the collection 🏎️ #Porsche911',
    created_at: '2024-01-14T10:30:00Z',
  },
  {
    id: 'post-d2',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Business meetings with a view 🏙️ NYC',
    created_at: '2024-01-11T15:45:00Z',
  },
  {
    id: 'post-d3',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Wine tasting in Bordeaux 🍷 1982 vintage',
    created_at: '2024-01-09T19:20:00Z',
  },
  {
    id: 'post-d4',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/1654748/pexels-photo-1654748.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Private jet to Monaco for the weekend ✈️',
    created_at: '2024-01-06T08:00:00Z',
  },
  {
    id: 'post-d5',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/3201761/pexels-photo-3201761.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Penthouse views 🌆 Home sweet home',
    created_at: '2024-01-03T20:15:00Z',
  },
  {
    id: 'post-d6',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/1591056/pexels-photo-1591056.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Collecting moments, not things 🌍',
    created_at: '2023-12-30T16:30:00Z',
  },
  {
    id: 'post-d7',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Rolex GMT Master II 🕐 Time is precious',
    created_at: '2023-12-27T11:00:00Z',
  },
  {
    id: 'post-d8',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/2467287/pexels-photo-2467287.jpeg?auto=compress&cs=tinysrgb&w=800',
    caption: 'Cigar & cognac evening 🥃',
    created_at: '2023-12-24T21:45:00Z',
  },
];

export const activities: Activity[] = [
  {
    id: 'activity-1',
    daddy_id: 'daddy-1',
    title: 'Weekend in Santorini',
    description: 'Private villa with infinity pool, sunset dinner at Ammoudi Bay, yacht day trip around the caldera',
    image_url: 'https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Santorini, Greece',
    likes_count: 234,
    created_at: '2024-01-16T10:00:00Z',
    liked: true,
  },
  {
    id: 'activity-2',
    daddy_id: 'daddy-2',
    title: 'Fashion Week Paris VIP',
    description: 'Front row seats at Chanel & Dior shows, exclusive after-party access, shopping at Avenue Montaigne',
    image_url: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Paris, France',
    likes_count: 567,
    created_at: '2024-01-15T14:30:00Z',
    liked: false,
  },
  {
    id: 'activity-3',
    daddy_id: 'daddy-3',
    title: 'Monaco Grand Prix Experience',
    description: 'Yacht viewing, paddock access, champagne brunch, gala dinner with drivers',
    image_url: 'https://images.pexels.com/photos/70912/pexels-photo-70912.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Monaco',
    likes_count: 892,
    created_at: '2024-01-14T09:15:00Z',
    liked: true,
  },
  {
    id: 'activity-4',
    daddy_id: 'daddy-1',
    title: 'Michelin Star Tour',
    description: '3-day culinary journey through French Riviera. 5 Michelin-starred restaurants, private chef experience',
    image_url: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'French Riviera',
    likes_count: 421,
    created_at: '2024-01-13T16:45:00Z',
    liked: false,
  },
  {
    id: 'activity-5',
    daddy_id: 'daddy-2',
    title: 'Coachella VIP Package',
    description: 'Private suite, backstage access, meet & greet with artists, helicopter transport',
    image_url: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'California, USA',
    likes_count: 1203,
    created_at: '2024-01-12T11:20:00Z',
    liked: true,
  },
];

export const activityComments: Record<string, ActivityComment[]> = {
  'activity-1': [
    {
      id: 'comment-1',
      activity_id: 'activity-1',
      user_id: 'baby-2',
      content: 'This looks absolutely amazing! 😍',
      created_at: '2024-01-16T11:30:00Z',
      user: otherUsers[1],
    },
    {
      id: 'comment-2',
      activity_id: 'activity-1',
      user_id: 'baby-1',
      content: 'Dream destination! 🌅',
      created_at: '2024-01-16T12:15:00Z',
      user: currentBabyUser,
    },
  ],
  'activity-3': [
    {
      id: 'comment-3',
      activity_id: 'activity-3',
      user_id: 'baby-3',
      content: 'Bucket list! Who wants to take me? 🏎️',
      created_at: '2024-01-14T10:30:00Z',
      user: otherUsers[4],
    },
  ],
  'activity-5': [
    {
      id: 'comment-4',
      activity_id: 'activity-5',
      user_id: 'baby-1',
      content: 'This would be incredible! 🎵',
      created_at: '2024-01-12T13:45:00Z',
      user: currentBabyUser,
    },
  ],
};

export const messages: Message[] = [
  {
    id: 'msg-1',
    sender_id: 'daddy-1',
    recipient_id: 'baby-1',
    content: 'Hi Emma! I saw you liked the Santorini experience. Would you be interested in joining me next month?',
    created_at: '2024-01-16T15:30:00Z',
  },
  {
    id: 'msg-2',
    sender_id: 'baby-1',
    recipient_id: 'daddy-1',
    content: 'Hi Alexandre! Yes, that sounds absolutely amazing! 😊',
    created_at: '2024-01-16T15:45:00Z',
  },
  {
    id: 'msg-3',
    sender_id: 'daddy-1',
    recipient_id: 'baby-1',
    content: 'Perfect! I\'ll arrange everything. We leave on the 15th. Pack light, luxury casual 😉',
    created_at: '2024-01-16T16:00:00Z',
  },
  {
    id: 'msg-4',
    sender_id: 'baby-1',
    recipient_id: 'daddy-1',
    content: 'I can\'t wait! Thank you so much for this opportunity! ✨',
    created_at: '2024-01-16T16:15:00Z',
  },
  {
    id: 'msg-5',
    sender_id: 'daddy-2',
    recipient_id: 'baby-1',
    content: 'Hey Emma, loved your Paris photos! Would you like to join me for Fashion Week?',
    created_at: '2024-01-15T18:20:00Z',
  },
  {
    id: 'msg-6',
    sender_id: 'baby-1',
    recipient_id: 'daddy-2',
    content: 'Hi Thomas! That would be a dream come true! 😍',
    created_at: '2024-01-15T18:35:00Z',
  },
  {
    id: 'msg-7',
    sender_id: 'daddy-2',
    recipient_id: 'baby-1',
    content: 'Great! I have front row seats for Chanel. See you there!',
    created_at: '2024-01-15T18:50:00Z',
  },
];

export const stories: Story[] = [
  {
    id: 'story-1',
    user_id: 'daddy-1',
    image_url: 'https://images.pexels.com/photos/2467287/pexels-photo-2467287.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_private: false,
    created_at: '2024-01-16T20:00:00Z',
    user: currentDaddyUser,
  },
  {
    id: 'story-2',
    user_id: 'daddy-2',
    image_url: 'https://images.pexels.com/photos/3593922/pexels-photo-3593922.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_private: false,
    created_at: '2024-01-16T19:30:00Z',
    user: otherUsers[0],
  },
  {
    id: 'story-3',
    user_id: 'baby-2',
    image_url: 'https://images.pexels.com/photos/1024967/pexels-photo-1024967.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_private: false,
    created_at: '2024-01-16T18:45:00Z',
    user: otherUsers[1],
  },
  {
    id: 'story-4',
    user_id: 'daddy-3',
    image_url: 'https://images.pexels.com/photos/1654748/pexels-photo-1654748.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_private: true,
    created_at: '2024-01-16T18:00:00Z',
    user: otherUsers[2],
  },
  {
    id: 'story-5',
    user_id: 'baby-1',
    image_url: 'https://images.pexels.com/photos/1371360/pexels-photo-1371360.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_private: false,
    created_at: '2024-01-16T17:30:00Z',
    user: currentBabyUser,
  },
];
